- forms.md
This is a composable validation library I wrote to work with redux form, but it's general enough to be used on its own too.
> Add link to revalidate.

- side-effects.md
How do you like adding redux-io to side-effects, since it's really what redux-io is for?
> adds redux-io to side-effects

- actions.md
I have another Redux lib for actions if you'll consider it. Redux Glue allows you to "glue" actions together instead of say wrapping them in a function. The lib comes with helper functions for testing the glued actions more easily too.
> Add redux-glue

- testing.md
How do you feel about adding this little tool for testing redux-saga?
[redux-saga-test](https://github.com/stoeffel/redux-saga-test)
> adds redux-saga-test

- apps-and-examples.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
> Add CarteJaune to the applications list

- action-reducer-generators.md
These are an emerging set of solutions from my experiences at [crosschx](https://github.com/crosschx)
> Add cx-redux-utils

- apps-and-examples.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
> Capital P dangit

- forms.md
> Remove dupe cape-io/redux-field

- side-effects.md
This a router library for redux-saga. It allows you to run others sagas based on route changes. It can also work alongside react-router.
```js
import { router, createBrowserHistory } from 'redux-saga-router';
const history = createBrowserHistory();
const routes = {
// Method syntax
*'/users'() {
const users = yield call(fetchUsers);
yield put(setUsers(users));
},
// Or long form with function expression
'/users/:id': function* userSaga({ id }) {
const user = yield call(fetchUser, id);
yield put(setCurrentUser(user));
},
};
function* mainSaga() {
const data = yield call(fetchInitialData);
yield put(ready(data));
yield* router(history, routes);
}
```
> Add link to redux-saga-router

- testing.md
redux-saga-test-plan has received a ton of updates over the past several weeks. I was hoping to simplify the description if possible. Thanks!
> Update redux-saga-test-plan description

- routing.md
Fix duplicated `redux-reroute` links.
> Remove duplicated links

- action-reducer-generators.md
Append redux-candy.
(I append Line 146-150 with github browser, and auto converted Line 129 encoding.)
> Add redux-candy

- routing.md
i'm the creator of this package and I moved it to its new home.
> move celebvidy/pure-redux-router to faceyspacey/pure-redux-router

- routing.md
I just published an in depth analysis of the state of routing in Redux that you might find interesting:
https://medium.com/@faceyspacey/pre-release-redux-first-router-a-step-beyond-redux-little-router-cd2716576aea
...I think i actually just tweeted you. I didn't realize you were the same guy. ..in that case, i really look forward to hearing what you have to say about what I've done here. I've bee in a vacuum for too long with my solution here.
> I changed the name of my router, pure-redux-router to redux-first-router

- reducers.md
Create redux reducers for async behaviors of multiple actions.
> feat(reducers): add redux-reducer-async

- immutable-data.md
https://github.com/hydux/hydux-mutator
> Add hydux-mutator

- immutable-data.md
Sorry, I forgot to copy spaces...
> Fix spaces

- immutable-data.md
Hello,
We would like to add [immutad●t](https://github.com/Zenika/immutadot) to the already long list of Immutable Update Utilities.
Thx for your time
> Add immutadot to Immutable Update Utilities

- immutable-data.md
https://github.com/phenyl-js/phenyl/tree/master/modules/power-assign
> Add power-assign to Immutable Update Utilities

- entity-collection-management.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
> Add BlueChip to entity-collection-management

- immutable-data.md
The link is broken, I'm not sure if this is the same library or not
https://github.com/giftofjehovah/redux-pipe
> Remove redux-pipe

- use-cases.md
I'm the author - wrote it and use it in several public browser extensions :)
> Add redux-browser-extension-sync to assorted

- middleware.md
https://github.com/taehwanno/redux-user-timing
> Add redux-user-timing middleware

- middleware-sockets-adapters.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
> Add React-Redux-Websocket

- use-cases.md
> remove redux-security (404)
